add font library
kubesphere/s2i-java-runtimeImage pull request #15
Opened 2022-03-10 10:38 UTC by Feeeenng

images not font library, may have font error. example
```
java.lang.NullPointerException at sun.awt.FontConfiguration.getVersion
```

2022-03-11 03:11 UTC, JohnNiang requested changes

2022-03-11 03:11 UTC, JohnNiang commented on tomcat85-java8/Dockerfile
> +RUN apk add --update ttf-dejavu fontconfig \
Same as above.

2022-03-11 03:11 UTC, JohnNiang commented on java11/Dockerfile
> +RUN apt update && apt -y install fontconfig
I suggest removing apt cache after installing. Please refer to https://gist.github.com/marvell/7c812736565928e602c4.

2022-03-11 03:11 UTC, JohnNiang commented on tomcat85-java11/Dockerfile
> +RUN apt update && apt -y install fontconfig
Same as above.

2022-03-11 03:13 UTC, JohnNiang commented
/cc @kubesphere/sig-devops

2022-03-13 06:00 UTC, Feeeenng commented on java8/Dockerfile
> +RUN apk add --update ttf-dejavu fontconfig \
ok

2022-03-14 01:16 UTC, JohnNiang commented
Thanks for your first contribution!
/lgtm

2022-03-14 01:25 UTC, LinuxSuRen commented
/kind tide/merge-method-squash

2022-03-14 01:27 UTC, LinuxSuRen reviewed
/lgtm

This is great. Thanks for your time! @Feeeenng

2022-03-14 01:28 UTC, merged